# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LogSumExp <- function(logV) {
    .Call(`_classNB_LogSumExp`, logV)
}

C_sum2Mat <- function(A, B) {
    .Call(`_classNB_C_sum2Mat`, A, B)
}

ParamVec <- function(A_, B_, C_, D_) {
    .Call(`_classNB_ParamVec`, A_, B_, C_, D_)
}

OrdParam <- function(initPr, transPr, esAvg, eSize, eProb) {
    .Call(`_classNB_OrdParam`, initPr, transPr, esAvg, eSize, eProb)
}

ForwardBackward_HMM <- function(initPr, transPr, emisPr) {
    .Call(`_classNB_ForwardBackward_HMM`, initPr, transPr, emisPr)
}

EmisPr_NB <- function(X, eSize, eProb) {
    .Call(`_classNB_EmisPr_NB`, X, eSize, eProb)
}

EmisPr_mixNB <- function(X, component, eWeight, eSize, eProb) {
    .Call(`_classNB_EmisPr_mixNB`, X, component, eWeight, eSize, eProb)
}

EM_NB <- function(X, initPr, transPr, eSize, eProb, iterMax = 500L, EPSILON = 1.0E-7) {
    .Call(`_classNB_EM_NB`, X, initPr, transPr, eSize, eProb, iterMax, EPSILON)
}

Viterbi_HMM <- function(initPr_, transPr_, emisPr_) {
    .Call(`_classNB_Viterbi_HMM`, initPr_, transPr_, emisPr_)
}

InitEM <- function(X, nbS) {
    .Call(`_classNB_InitEM`, X, nbS)
}

HMM_NB_CF <- function(X, nbS, viterbi = TRUE, initPr = NULL, transPr = NULL, eSize = NULL, eProb = NULL, iterMax = 500L, EPSILON = 1.0E-7) {
    .Call(`_classNB_HMM_NB_CF`, X, nbS, viterbi, initPr, transPr, eSize, eProb, iterMax, EPSILON)
}

HMM_NB_NS <- function(X, nbS, viterbi = TRUE, iterMax = 5000L, EPSILON = 1e-7) {
    .Call(`_classNB_HMM_NB_NS`, X, nbS, viterbi, iterMax, EPSILON)
}

mixNB_NB_CF <- function(X, nbS, iterMax = 15000L, EPSILON = 1e-7) {
    .Call(`_classNB_mixNB_NB_CF`, X, nbS, iterMax, EPSILON)
}

mixNB_NB_NS <- function(X, nbS, iterMax = 15000L, EPSILON = 1e-7) {
    .Call(`_classNB_mixNB_NB_NS`, X, nbS, iterMax, EPSILON)
}

